#!/bin/bash
if [ -f ~/.config/polybar/scripts/stat ]; then
    temp=$(cat ~/.config/polybar/scripts/stat)
    temp=$(($temp + 1))
    echo "$temp" > ~/.config/polybar/scripts/stat

else
    echo 1 > ~/.config/polybar/scripts/stat
fi
